/home/meshcore/trace-mon/logs/trace-mon.log
/home/meshcore/trace-mon/logs/cron-errors.log
/home/meshcore/trace-mon/logs/cron-status.log {
    weekly
    rotate 8
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
}
